<script setup lang="ts">
import { computed, onMounted, ref } from 'vue'
import { ElMessage, ElMessageBox } from 'element-plus'
import { ArrowDownBold, ArrowUpBold, CircleCheck, Clock, Edit, Link, Plus, Refresh, View } from '@element-plus/icons-vue'
import { useRouter } from 'vue-router'
import PageHeader from '../../components/common/PageHeader.vue'
import EmptyState from '../../components/common/EmptyState.vue'
import StatusTag from '../../components/common/StatusTag.vue'
import WrittenTestDialog from '../../dialogs/WrittenTestDialog.vue'
import InterviewDialog from '../../dialogs/InterviewDialog.vue'
import type { InterviewRound } from '../../types/interview'
import type { WorkflowNodeResult } from '../../types/writtenTest'
import type { WorkflowNode, WorkflowJob } from '../../services/recruitmentWorkflowService'
import { finishAsOffer, finishAsRejected, finishAsWithdrawn, interviewRoundLabels, listWorkflowJobs, updateWorkflowNode, workflowResultLabels, workflowStatusLabels } from '../../services/recruitmentWorkflowService'
import { isTauriRuntime } from '../../services/databaseService'
import { displayDateTime } from '../../utils/dateTime'
import { isWebLink, openWebLink } from '../../utils/link'

const router=useRouter(),rows=ref<WorkflowJob[]>([]),loading=ref(false),keyword=ref(''),scope=ref<'ACTIVE'|'HISTORY'|'ALL'>('ACTIVE'),expanded=ref<number[]>([])
const writtenDialog=ref<InstanceType<typeof WrittenTestDialog>>(),interviewDialog=ref<InstanceType<typeof InterviewDialog>>()
const filtered=computed(()=>rows.value.filter(row=>{const matches=!keyword.value.trim()||`${row.companyName} ${row.jobName}`.toLowerCase().includes(keyword.value.trim().toLowerCase());const inScope=scope.value==='ALL'||(scope.value==='ACTIVE'?row.stage==='PROCESS':row.stage!=='PROCESS');return matches&&inScope}))
async function load(){if(!isTauriRuntime())return;loading.value=true;try{rows.value=await listWorkflowJobs()}catch(error){ElMessage.error(error instanceof Error?error.message:'读取招聘流程失败')}finally{loading.value=false}}
function toggle(jobId:number){expanded.value=expanded.value.includes(jobId)?expanded.value.filter(id=>id!==jobId):[...expanded.value,jobId]}
function toneForNode(node?:WorkflowNode):'info'|'danger'|'success'|'warning'|'primary'{if(!node)return'info';if(node.result==='FAILED')return'danger';if(node.result==='PASSED')return'success';if(node.status==='SCHEDULED')return'warning';return'primary'}
async function chooseNext(command:string,row:WorkflowJob){
  if(command==='OFFER'){try{await ElMessageBox.confirm(`确认将“${row.companyName} · ${row.jobName}”结束为 Offer？`,'确认 Offer',{type:'success',confirmButtonText:'确认 Offer',cancelButtonText:'取消'})}catch{return}await finishAsOffer(row.jobId);ElMessage.success('招聘流程已完成，岗位已更新为 Offer');await load();return}
  if(command==='REJECTED'){try{const answer=await ElMessageBox.prompt('请填写淘汰原因','标记淘汰',{inputPlaceholder:'例如：二面后未通过',confirmButtonText:'确认淘汰',cancelButtonText:'取消',inputValidator:(value:string)=>value.trim()?true:'请填写淘汰原因'});await finishAsRejected(row.jobId,answer.value.trim())}catch{return}ElMessage.success('岗位已标记为淘汰');await load();return}
  if(command==='WITHDRAWN'){try{await ElMessageBox.confirm(`确认主动放弃“${row.companyName} · ${row.jobName}”的招聘流程？`,'主动放弃',{type:'warning',confirmButtonText:'确认放弃',cancelButtonText:'取消'})}catch{return}await finishAsWithdrawn(row.jobId);ElMessage.success('岗位已标记为主动放弃');await load();return}
  if(command==='WRITTEN_TEST'){writtenDialog.value?.open(undefined,row.jobId);return}
  const round=command as InterviewRound
  if(!row.history.length&&round!=='FIRST'){try{await ElMessageBox.confirm(`当前岗位尚未记录前面的面试轮次。确认直接创建“${interviewRoundLabels[round]}”吗？`,'跳过前置轮次',{type:'warning',confirmButtonText:'仍然创建',cancelButtonText:'取消'})}catch{return}}
  interviewDialog.value?.open(undefined,row.jobId,round)
}
async function complete(node:WorkflowNode){try{await updateWorkflowNode(node,'COMPLETED','PENDING');ElMessage.success('流程已标记完成，请填写结果');await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'更新失败')}}
async function changeResult(node:WorkflowNode,result:WorkflowNodeResult){try{await updateWorkflowNode(node,'COMPLETED',result);ElMessage.success(result==='FAILED'?'未通过，岗位已自动淘汰':'流程结果已更新');await load()}catch(error){ElMessage.error(error instanceof Error?error.message:'更新结果失败')}}
function edit(node:WorkflowNode){if(node.nodeType==='WRITTEN_TEST')writtenDialog.value?.open({...node,companyName:'',jobName:'',testType:''} as any);else interviewDialog.value?.open({...node,companyName:'',jobName:'',interviewType:''} as any)}
onMounted(load)
</script>
<template><div class="page-stack"><PageHeader title="招聘流程" subtitle="统一管理已进入后续流程岗位的笔试、面试及招聘进展"><el-button :icon="Refresh" title="刷新招聘流程" @click="load">刷新</el-button></PageHeader>
  <el-alert v-if="!isTauriRuntime()" title="当前是界面预览；流程数据仅在 Windows 客户端内启用。" type="info" show-icon :closable="false"/>
  <div class="toolbar"><el-input v-model="keyword" clearable placeholder="搜索企业或岗位"/><el-segmented v-model="scope" :options="[{label:'进行中',value:'ACTIVE'},{label:'历史结果',value:'HISTORY'},{label:'全部',value:'ALL'}]"/></div>
  <section v-loading="loading" class="workflow-list"><article v-for="row in filtered" :key="row.jobId" class="workflow-card" :class="`stage-${row.stage.toLowerCase()}`"><div class="workflow-main">
    <div class="identity"><span class="process-icon"><el-icon><Clock/></el-icon></span><span><strong>{{ row.companyName }}</strong><small>{{ row.jobName }}<template v-if="row.location"> · {{ row.location }}</template></small></span></div>
    <div class="current"><small>当前流程</small><strong>{{ row.currentNode?.label||'尚未安排' }}</strong><span>{{ row.currentNode?displayDateTime(row.currentNode.scheduledAt,row.currentNode.timeTbd):'待安排' }}</span></div>
    <div class="node-state"><small>流程状态</small><StatusTag :type="toneForNode(row.currentNode)">{{ row.currentNode?workflowStatusLabels[row.currentNode.status]:'待安排' }}</StatusTag></div><div class="node-state"><small>当前结果</small><StatusTag :type="row.currentNode?.result==='FAILED'?'danger':row.currentNode?.result==='PASSED'?'success':'info'">{{ row.currentNode?workflowResultLabels[row.currentNode.result]:'—' }}</StatusTag></div>
    <div class="summary"><small>流程摘要</small><span>已投递<template v-for="node in row.history" :key="node.key"> → {{ node.label }}</template></span></div>
    <div class="actions"><el-button :icon="View" @click="router.push(`/jobs/${row.jobId}`)">岗位</el-button><el-button v-if="row.currentNode?.status==='SCHEDULED'" :icon="CircleCheck" type="primary" plain @click="complete(row.currentNode)">完成</el-button><el-select v-if="row.currentNode?.status==='COMPLETED'&&row.currentNode.result==='PENDING'" placeholder="填写结果" @change="changeResult(row.currentNode!,$event as WorkflowNodeResult)"><el-option label="通过" value="PASSED"/><el-option label="未通过" value="FAILED"/></el-select>
      <el-tooltip :disabled="row.canAddNext" :content="row.nextBlockedReason"><span><el-dropdown :disabled="!row.canAddNext" trigger="click" @command="chooseNext($event,row)"><el-button :icon="Plus" type="primary" :disabled="!row.canAddNext">{{ row.history.length?'添加下一步':'安排第一个流程' }}</el-button><template #dropdown><el-dropdown-menu><el-dropdown-item command="WRITTEN_TEST">笔试</el-dropdown-item><el-dropdown-item command="FIRST">一面</el-dropdown-item><el-dropdown-item command="SECOND">二面</el-dropdown-item><el-dropdown-item command="THIRD">三面</el-dropdown-item><el-dropdown-item command="HR">HR 面</el-dropdown-item><el-dropdown-item command="FINAL">终面</el-dropdown-item><el-dropdown-item command="OTHER">其他面试</el-dropdown-item><template v-if="row.history.length"><el-dropdown-item command="OFFER" divided>Offer</el-dropdown-item><el-dropdown-item command="WITHDRAWN">主动放弃</el-dropdown-item><el-dropdown-item command="REJECTED">标记淘汰</el-dropdown-item></template></el-dropdown-menu></template></el-dropdown></span></el-tooltip><el-button :icon="expanded.includes(row.jobId)?ArrowUpBold:ArrowDownBold" text :title="expanded.includes(row.jobId)?'收起流程':'查看流程'" @click="toggle(row.jobId)"/></div>
  </div><div v-show="expanded.includes(row.jobId)" class="history"><div class="history-line submitted"><i/><span><strong>已投递</strong><small>{{ row.submittedAt||row.applicationDate||'历史投递时间未记录' }}</small></span></div><div v-for="node in row.history" :key="node.key" class="history-line"><i/><span><strong>{{ node.label }}</strong><small>{{ displayDateTime(node.scheduledAt,node.timeTbd) }} · {{ workflowStatusLabels[node.status] }} · {{ workflowResultLabels[node.result] }}</small></span><el-button v-if="node.meetingUrl&&isWebLink(node.meetingUrl)" :icon="Link" link type="primary" title="打开流程链接" @click="openWebLink(node.meetingUrl)"/><el-button :icon="Edit" link title="编辑流程" @click="edit(node)"/></div><div v-if="!row.history.length" class="missing-history">尚未安排具体流程。旧阶段数据没有详细记录时，可从这里补录真实节点。</div></div></article><EmptyState v-if="!filtered.length" title="暂无招聘流程" description="在岗位库把已投递岗位改为“面试/笔试”后，会出现在这里。"/></section>
  <WrittenTestDialog ref="writtenDialog" @saved="load"/><InterviewDialog ref="interviewDialog" @saved="load"/>
</div></template>
<style scoped lang="scss">.page-stack{display:grid;gap:16px}.toolbar{display:flex;align-items:center;justify-content:space-between;gap:12px;padding:12px 14px;border:1px solid var(--border-color);border-radius:8px;background:var(--bg-card)}.toolbar .el-input{max-width:360px}.workflow-list{display:grid;gap:10px;min-height:360px}.workflow-card{overflow:hidden;border:1px solid var(--border-color);border-left:4px solid var(--purple);border-radius:8px;background:var(--bg-card);box-shadow:var(--shadow-card)}.stage-offer{border-left-color:var(--success)}.stage-rejected{border-left-color:var(--danger)}.workflow-main{display:grid;grid-template-columns:minmax(220px,1.35fr) 150px 100px 100px minmax(180px,1fr) auto;align-items:center;gap:14px;padding:16px}.identity{display:flex;min-width:0;align-items:center;gap:11px}.identity>span:last-child{display:grid;min-width:0;gap:4px}.identity strong,.identity small,.summary span{overflow:hidden;text-overflow:ellipsis;white-space:nowrap}.identity small,.current small,.node-state small,.summary small{color:var(--text-tertiary);font-size:11px}.process-icon{display:grid;width:40px;height:40px;flex:0 0 40px;place-items:center;border-radius:7px;color:var(--purple);background:color-mix(in srgb,var(--purple) 12%,var(--bg-card))}.current,.node-state,.summary{display:grid;gap:5px;min-width:0}.current span,.summary span{color:var(--text-secondary);font-size:12px}.actions{display:flex;align-items:center;justify-content:flex-end;gap:6px}.actions .el-button+.el-button{margin-left:0}.actions .el-select{width:104px}.history{display:grid;border-top:1px solid var(--border-color);padding:10px 20px 15px 54px;background:color-mix(in srgb,var(--purple) 3%,var(--bg-card))}.history-line{position:relative;display:flex;min-height:52px;align-items:center;gap:10px;border-left:2px solid var(--border-color);padding:5px 8px 5px 22px}.history-line i{position:absolute;left:-6px;width:10px;height:10px;border:2px solid var(--bg-card);border-radius:50%;background:var(--purple)}.history-line span{display:grid;flex:1;gap:3px}.history-line small{color:var(--text-secondary)}.submitted i{background:var(--teal)}.missing-history{border:1px dashed var(--border-color);border-radius:7px;padding:16px;color:var(--text-secondary)}@media(max-width:1250px){.workflow-main{grid-template-columns:minmax(220px,1.4fr) 140px 90px 90px auto}.summary{display:none}}@media(max-width:900px){.workflow-main{grid-template-columns:1fr 1fr}.identity,.actions{grid-column:1/-1}.actions{justify-content:flex-start}}</style>
